#ifndef _YOLOX_CPP_CONFIG_H_
#define _YOLOX_CPP_CONFIG_H_

/* #undef ENABLE_OPENVINO */
#define ENABLE_TENSORRT
/* #undef ENABLE_ONNXRUNTIME */
/* #undef ENABLE_TFLITE */

#endif // _YOLOX_CPP_CONFIG_H_
