launch: #起動パラメータ
  ros__parameters:
    slcan: true
    scan: true
    trajectory_planner: true
    yolox_launch: true

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    initial_pose: [0.35, 0.55, 0.0]  #初期位置[x,y,yaw]
    2nd_initial_pose: [5.5, 0.35, 0.0]  #2つ目の初期位置[x,y,yaw]
    tf_laser2robot: [0.0,0.0,0.0,  0.0,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]

    court_color: "blue" #コート情報

    # 自動の並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max_vel: 2.6
    linear_max_acc: 2.3
    linear_max_dec: 2.3
    linear_max_jer: 0.0
    # 回転  速度[deg/sint x, int y, const std::vector<double> point1, const std::vector<double> point2],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max_vel: 100.0
    angular_max_acc: 360.0
    angular_max_dec: 360.0
    angular_max_jer: 0.0
    
    canid:
      #000番台(根幹情報)
      emergency: 0x000
      heartbeat: 0x001
      restart: 0x002
      calibrate: 0x003
      reset: 0x004
      emergency_state: 0x005
      #100番台(足回り)
      linear: 0x100
      angular: 0x101
      odom_linear_x: 0x110
      odom_linear_y: 0x111
      odom_angular: 0x112
      init_angular: 0x120
      steer_reset: 0x130
      #200番台(上物)
      #ハンド
      paddy_collect: 0x200
      paddy_install: 0x201
      paddy_convergence: 0x202
      #網
      net: 0x210
      net_convergence: 0x211
      #自動化
      tof: 0x220
      hand_lift: 0x221
      hand_fb: 0x222
      hand_wrist: 0x223
      suction: 0x224
      #
      base_state: 0x230
      strage_state: 0x231
      strage_state2: 0x232
      transfer_state: 0x233
      silo_state: 0x234
      silo_state2: 0x235
        
    port:
      joy_main: 50000

    convergence_ms: 100 #収束周期[ms]
    heartbeat_ms: 100 #ハートビート周期[ms]
    #リスタート、緊急、足回りの手自動、上物の手自動、手動の射角、ボタンのカラー情報
    defalt_restart_flag: false
    defalt_emergency_flag: false
    defalt_move_autonomous_flag: false
    defalt_slow_speed_flag: false
    #収束の初期値
    defalt_spline_convergence: false
    defalt_arm_convergence: false
    defalt_net_convergence: false

controller_interface_node:
  ros__parameters:
    # 手動の高速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    high_linear_max_vel: 1.5
    high_linear_max_acc: 3.0
    high_linear_max_dec: 2.0
    # 手動の低速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    slow_linear_max_vel: 0.5
    slow_linear_max_acc: 1.5
    slow_linear_max_dec: 1.5
    # 手動の回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2]
    angular_max_vel: 100.0
    angular_max_acc: 360.0
    angular_max_dec: 360.0
    
    interval_ms: 50
    start_ms: 3000
    controller_ms: 100
    mainboard_ms: 200

    connection_check: false

rasnac_localization:
  ros__parameters:
    plot_mode: true #実機のときはfalse
    laser_weight: 1.0 #lidarの重み->値を大きくするとlidarが優先される
    odom_weight_liner: 2.0e-3 #値が大きくなると共分散が小さくなる 
    odom_weight_angler: 3.0e-4
    voxel_size: 0.06
    trial_num: 50
    inlier_dist_threshold: 0.012
    inlier_length_threshold: 0.5 #インライアのしきい値
    second_ransac: false           #2回ransacをするか
    robot_type: "R2"

spline_pid_node:
  ros__parameters:
    interval_ms: 20     #サイクル周期[ms]
    curvature_attenuation_rate: 0.0 #曲率の速度の減衰>=0 (0だと減衰なし)
    linear_planner_vel_limit_gain: 1.0  #速度計画機の速度上限値にかけるゲイン

    linear_planner_gain: 1.2 #並進速度計画機ゲイン
    linear_pos_gain: 2.7  #並進位置ズレのゲイン
    linear_pos_diff_gain: 0.8
    linear_pos_integral_gain: 0.01  #並進位置ズレの積分ゲイン

    angular_planner_gain: 1.0 #回転速度計画機ゲイン
    angular_pos_gain: 2.5 #回転位置ズレのゲイン
    angular_pos_integral_gain: 0.01 #回転位置ズレの積分ゲイン

    linear_pos_tolerance: 0.02  #並進到達位置の許容誤差[m]
    angular_pos_tolerance: 2.0  #回転到達位置の許容誤差[deg]
    waypoint_tolerance: [0.04, 0.04, 5.0]

spline_trajectories_node:
  ros__parameters:
    resolution: 0.01  #起動点の分解能[m]

detection_interface_node:
  ros__parameters:
    #ST系の行ったときの吸引判定
    front_suction_check_point: [600, 800] #[500, 675] #[y,x]
    back_suction_check_point: [225, 800] #[225, 730] #[y,x]
    front_depth_suction_check_value: 200
    back_depth_suction_check_value: 350

    realsense_max_x: 900
    realsense_min_x: 300
    realsense_max_y: 700

    #c1caeraでc2nodeから見たときのxの閾値
    c2node_threshold_x: 1000

    #realsenseがc3 or c6nodeから見たボール1個分のy(ここの数値を下げることでc3,c6から見えるボールが例:3列から2列になる。上げると見えるボールが例:1列から2列になる)
    str_range_y_C3orC5: 130 #130  
    str_range_x_C3orC5: 185 #180

sequencer_node:
  ros__parameters:
    strage_dist: [0.38 , 0.20] #m
    suction_wait: 1.0 #ms 
    silo_wait: 1.0 #ms 