launch: #起動パラメータ
  ros__parameters:
    slcan: true
    scan: false
    trajectory_planner: true
    

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    initial_pose: [0.5, 0.5, 0.0]  #初期位置[x,y,yaw]
    2nd_initial_pose: [5.5, 0.35, 0.0]  #2つ目の初期位置[x,y,yaw]
    tf_laser2robot: [0.3,0.0,0.0,  3.14159,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]
    court_color: "red" #コート情報

    # 自動の並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max_vel: 3.0
    linear_max_acc: 4.0
    linear_max_dec: 4.0
    linear_max_jer: 0.0
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max_vel: 270.0
    angular_max_acc: 230.0
    angular_max_dec: 230.0
    angular_max_jer: 0.0
    
    canid:
      #000番台(根幹情報)
      emergency: 0x000
      heartbeat: 0x001
      restart: 0x002
      calibrate: 0x003
      reset: 0x004
      #100番台(足回り)
      linear: 0x100
      angular: 0x101
      odom_linear: 0x110
      odom_angular: 0x111
      init_angular: 0x120
      steer_reset: 0x130
      #200番台(上物)
      #ハンド
      paddy_collect: 0x200
      paddy_install: 0x201
      #デジタルボタン
      main_button: 0x230
        
    port:
      joy_main: 50000
      pole_share: 53000
      spline_state: 55000
      robot_state: 57000
      
    ip:
      r1_pc: "192.168.1.2"
      r2_pc: "192.168.1.3"

spline_pid_node:
  ros__parameters:
    interval_ms: 20     #サイクル周期[ms]
    curvature_attenuation_rate: 0.0 #曲率の速度の減衰>=0 (0だと減衰なし)
    linear_planner_vel_limit_gain: 0.6  #速度計画機の速度上限値にかけるゲイン

    linear_planner_gain: 0.1 #並進速度計画機ゲイン
    linear_pos_gain: 10.0  #並進位置ズレのゲイン
    linear_pos_diff_gain: 1.0
    linear_pos_integral_gain: 0.03  #並進位置ズレの積分ゲイン

    angular_planner_gain: 1.0 #回転速度計画機ゲイン
    angular_pos_gain: 2.3 #回転位置ズレのゲイン
    angular_pos_integral_gain: 0.03  #回転位置ズレの積分ゲイン

    linear_pos_tolerance: 0.03  #並進到達位置の許容誤差[m]
    angular_pos_tolerance: 3.0  #回転到達位置の許容誤差[deg]

spline_trajectories_node:
  ros__parameters:
    resolution: 0.01  #起動点の分解能[m]

controller_interface_node:
  ros__parameters:
    # 手動の高速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    high_linear_max_vel: 1.0
    high_linear_max_acc: 2.0
    high_linear_max_dec: 2.0
    # 手動の低速　並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    slow_linear_max_vel: 0.5
    slow_linear_max_acc: 1.0
    slow_linear_max_dec: 1.0
    # 手動の回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2]
    angular_max_vel: 45.0
    angular_max_acc: 180.0
    angular_max_dec: 180.0
    
    heartbeat_ms: 100 #ハートビート周期[ms]
    convergence_ms: 100 #収束周期[ms]

    base_state_communication_ms: 100

    interval_ms: 50
    start_ms: 3000
    
    #リスタート、緊急、足回りの手自動、上物の手自動、手動の射角、ボタンのカラー情報
    defalt_restart_flag: true
    defalt_emergency_flag: true
    defalt_move_autonomous_flag: true
    defalt_arm_autonomous_flag: true
    defalt_slow_speed_flag: true
    defalt_color_information_flag: true

    #収束の初期値
    defalt_spline_convergence: true
    defalt_arm_calculator_convergence: true
    defalt_arm_convergence: true

    initial_pickup_state: "A"
    initial_inject_state: "B"

arm_interface_node:
  ros__parameters:
    tf_arm2robot: [0.0, 0.0] #射出機構のTF[x, y]
    strage_backside: [0.0, 0.0, 0.0] #ストレージエリアの[x, y, 高さ]
    strage_front: [0.1, 0.0, 0.0]

rasnac_localization:
  ros__parameters:
    plot_mode: true #実機のときはfalse
    laser_weight: 1.0 #lidarの重み->値を大きくするとlidarが優先される
    odom_weight_liner: 1.0e-5 #値が大きくなると共分散が小さくなる
    odom_weight_angler: 1.0e-5
    voxel_size: 0.05
    trial_num: 40
    inlier_dist_threshold: 0.01
    inlier_length_threshold: 1.0 #インライアのしきい値

sequencer_node:
  ros__parameters:
    select_algorithm: 0
    seedling_order: ["S0", "S1", "S2", "S3"]
    planting_order: ["P0", "P1", "P2", "P3", "P4", "P5", "P6", "P7"]
    harvesting_order: ["H0", "H1", "H2", "H3", "H4", "H5", "H6", "H7", "H8", "H9", "H10", "H11"]

injection_param_calculator_node:
  ros__parameters:
    mass: 0.157                          # リングの重量[kg]
    gravitational_accelerastion: 9.80665 # 重力加速度[m/s^2]
    air_resistance: 7.78e-3              # 空気抵抗係数[kg/s]
    foundation_hight: 0.0                # 射出機構の地面からの高さ[m]
    velocity_lim_max: 10.0               # 最大初速度[m/s]
    injection_angle: 45.0                # 射出角度[deg]
    max_loop: 100                        # ニュートン法のループ制限回数
