/ros2_laser_scan_merger:
  ros__parameters:
    flip1: true
    flip2: true
    inverse1: false
    inverse2: false
    laser1Alpha: -90.0
    laser1AngleMax: 180.0
    laser1AngleMin: -180.0
    laser1B: 0
    laser1G: 255
    laser1R: 255
    laser1XOff: 0.0
    laser1YOff: 0.275
    laser1ZOff: 0.0
    laser2Alpha: 90.0
    laser2AngleMax: 180.0
    laser2AngleMin: -180.0
    laser2B: 255
    laser2G: 255
    laser2R: 255
    laser2XOff: 0.0
    laser2YOff: -0.275
    laser2ZOff: 0.0
    pointCloudTopic: scan_cloud
    pointCloutFrameId: laser
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /scan_1st
    scanTopic2: /scan_2nd
    show1: true
    show2: true
    use_sim_time: false

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.00436332
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 0.0
    min_height: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 8.0
    range_min: 0.02
    scan_time: 0.025
    target_frame: laser
    transform_tolerance: 0.0
    use_inf: true
    use_sim_time: false
